#!/bin/bash
########################################################################################################################
# ██████╗  ██████╗ ████████╗███████╗██╗██╗     ███████╗███████╗
# ██╔══██╗██╔═══██╗╚══██╔══╝██╔════╝██║██║     ██╔════╝██╔════╝
# ██║  ██║██║   ██║   ██║   █████╗  ██║██║     █████╗  ███████╗
# ██║  ██║██║   ██║   ██║   ██╔══╝  ██║██║     ██╔══╝  ╚════██║
# ██████╔╝╚██████╔╝   ██║   ██║     ██║███████╗███████╗███████║
# ╚═════╝  ╚═════╝    ╚═╝   ╚═╝     ╚═╝╚══════╝╚══════╝╚══════╝
########################################################################################################################
set -xe
mkdir -p $HOME/tools $HOME/.tmp
DIR="$HOME/dotfiles"
CONFIG_DIR="$HOME/.config"
DOT_CONFIG="$DIR/config"
source $HOME/dotfiles/zsh/utils.sh
########################################################################################################################
##### python modules
pip3 install --user colour docker numpy pint inflect matplotlib fuzzywuzzy wheel meme

########################################################################################################################
##### core installs
ln -sf $DIR/nvim/ $CONFIG_DIR/nvim/
ln -sf $DIR/zsh/zshrc $HOME/.zshrc
ln -sf $DOT_CONFIG/tmux $CONFIG_DIR/tmux
ln -sf $DIR/idea/.ideavimrc $HOME/.ideavimrc
ln -sf $DOT_CONFIG/wezterm/wezterm.lua $HOME/.wezterm.lua

########################################################################################################################
##### gitconfig
ln -sf $DIR/git/gitconfig $HOME/.gitconfig

########################################################################################################################
##### fzf
function installfzf() {
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
}
checkcommand "fzf" installfzf
########################################################################################################################
##### brew
function installbrew() {
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    bash $HOME/dotfiles/setup/brew.sh
}
checkcommand "brew" installbrew
########################################################################################################################
##### node config
function installvolta() {
    curl https://get.volta.sh | bash
    volta install node@latest
    volta install yarn@1.22.22
    npm i -g pnpm ts-node yarn neovim
}
checkcommand "volta" installvolta
########################################################################################################################
##### other links
ln -sf $DOT_CONFIG/fd/.fdignore $HOME/.fdignore
ln -sf $DOT_CONFIG/starship.toml $CONFIG_DIR/starship.toml
ln -sf $DIR/dygma $HOME/Raise
ln -sf $DIR/config/alacritty/ $CONFIG_DIR
make
