#!/bin/bash
########################################################################################################################
# ██████╗  ██████╗ ████████╗███████╗██╗██╗     ███████╗███████╗
# ██╔══██╗██╔═══██╗╚══██╔══╝██╔════╝██║██║     ██╔════╝██╔════╝
# ██║  ██║██║   ██║   ██║   █████╗  ██║██║     █████╗  ███████╗
# ██║  ██║██║   ██║   ██║   ██╔══╝  ██║██║     ██╔══╝  ╚════██║
# ██████╔╝╚██████╔╝   ██║   ██║     ██║███████╗███████╗███████║
# ╚═════╝  ╚═════╝    ╚═╝   ╚═╝     ╚═╝╚══════╝╚══════╝╚══════╝
########################################################################################################################
set -xe
mkdir -p $HOME/tools $HOME/.tmp
mkdir -p $HOME/.config
DOTFILES_DIR="$HOME/dotfiles"
HOME_CONFIG_DIR="$HOME/.config"
DOTFILES_CONFIG_DIR="$DOTFILES_DIR/config"
source $HOME/dotfiles/zsh/utils.sh
sh <(curl -L https://nixos.org/nix/install) --daemon

########################################################################################################################
##### mise config
function installmise() {
    curl https://mise.run | sh
    ~/.local/bin/mise activate
    ~/.local/bin/mise use -g usage
    ~/.local/bin/mise use -g node
    ~/.local/bin/mise doctor
}
checkcommand "mise" installmise

########################################################################################################################
##### other links
function setupBat() {
    mkdir -p "$(bat --config-dir)/syntaxes"
    cd "$(bat --config-dir)/syntaxes"
    git clone https://github.com/tellnobody1/sublime-purescript-syntax
    ln -sf $DOTFILES_CONFIG_DIR/bat $HOME_CONFIG_DIR
}
setupBat

