if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


call plug#begin('~/.vim/bundle')
  Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
  Plug 'reewr/vim-monokai-phoenix'
  Plug 'Yggdroot/indentLine'
call plug#end()

let mapleader = " "

set antialias
set autoread
set encoding=utf-8
set expandtab
set hidden
set hlsearch
set ignorecase
set incsearch
set mouse=a
set nocompatible
set nowrap
set number
set smartcase
set smartindent


colorscheme monokai-phoenix
