search_shortcut: off
toggle_key: OFF
matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"
  - trigger: ":time"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%H:%M"

  - triggers: [":block:", ":mb:"]
    replace: |-
      ```$|$
      ```
    force_clipboard: true

  - triggers: [":code:", ":mc:"]
    replace: |-
      `$|$`
    force_clipboard: true

  - trigger: ":h1:"
    replace: "#"

  - trigger: ":h2:"
    replace: "##"

  - trigger: ":h3:"
    replace: "###"

  - trigger: ":h4:"
    replace: "####"

  - trigger: ":h5:"
    replace: "#####"

  - trigger: ":h6:"
    replace: "######"

  - trigger: ":bold:"
    replace: "**$|$**"

  - trigger: ":italic:"
    replace: "*$|$*"

  - trigger: ":strike:"
    replace: "~~$|$~~"

  - trigger: ":url:"
    replace: "[$|$]()"

  - triggers: [":image:", ":img:"]
    replace: "![]($|$)"

  - triggers: [":horizontal:", ":mh:"]
    replace: "___"

  - triggers: [":task:", ":mt:"]
    replace: "- [ ] "

  - triggers: [":taskdone:", ":mtd:"]
    replace: "- [x] "

  - triggers: [":collapse:", ":mcol:"]
    replace: |-
      <details>
      <summary></summary>
      
      $|$
      </details>
    force_clipboard: true