# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: github
completion:
    positional:
        - ["$carapace.tools.gh.OwnerRepositories"] # ${C_ARG0}
        - ["$carapace.tools.git.LsRemoteRefs({url: 'https://github.com/${C_ARG0}', branches: true, tags: true})"]
