---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "c_sharp",
      "css",
      "csv",
      "diff",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitcommit",
      "gitignore",
      "html",
      "http",
      "javascript",
      "jq",
      "json",
      "json5",
      "kdl",
      "lua",
      "luadoc",
      "markdown",
      "markdown_inline",
      "prisma",
      "query",
      "regex",
      "styled",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
      "zig",
    },
  },
}
