classic: false
date: date
dereference: false
hyperlink: always
indicators: false
size: short
total-size: false
color:
    when: always
    theme: custom
icons:
    when: always
    theme: fancy
    separator: " "
