classic: false
date: date
dereference: true
hyperlink: always
indicators: false
size: short
total-size: true
color:
  when: always
  theme: custom
icons:
  when: always
  theme: fancy
  separator: " "
