##############################################################################################################
## loader contract
# Prefer an explicitly configured checkout, but keep ~/.zshrc symlinks and direct
# sources relocatable by deriving the repository root from this file's path.
typeset -g _zshrc_source="${(%):-%N}"
export WORDCHARS='.*_-[]@~&;:!#$%^(){}<>/\//[\/]/ '
export WORDCHARS="${WORDCHARS/\//}"
[[ "$_zshrc_source" == /* ]] || _zshrc_source="$PWD/$_zshrc_source"
typeset -g _zshrc_root="${_zshrc_source:A:h:h:h}"
typeset -g DOTFILES="${DOTFILES:-$_zshrc_root}"
[[ -d "$DOTFILES/config/zsh" ]] || DOTFILES="$_zshrc_root"
export DOTFILES
if [[ -z "${DOTFILES_DIR:-}" || ! -d "$DOTFILES_DIR/config/zsh" ]]; then
    export DOTFILES_DIR="$DOTFILES"
else
    export DOTFILES_DIR
fi
export TS_SCRIPTS="${TS_SCRIPTS:-$DOTFILES/bin}"
unset _zshrc_source _zshrc_root

## exports
source "$DOTFILES/config/zsh/exports.sh"
source "$DOTFILES/config/zsh/utils.sh"
safeImport "$HOME/.local-exports.sh"

if [[ -o interactive && -t 1 ]]; then
    _zsh_restore_tty_output() {
        stty opost onlcr 2>/dev/null || true
    }
    autoload -Uz add-zsh-hook
    add-zsh-hook -d preexec _zsh_restore_tty_output 2>/dev/null
    add-zsh-hook -d precmd _zsh_restore_tty_output 2>/dev/null
    add-zsh-hook preexec _zsh_restore_tty_output
    add-zsh-hook precmd _zsh_restore_tty_output
    _zsh_restore_tty_output
fi
##############################################################################################################
## znap
(($+commands[mise])) && eval "$(command mise activate zsh)"
typeset -g ZNAP_DIR="${ZNAP_DIR:-$HOME/.znap}"
typeset -g ZNAP_ENTRYPOINT="$ZNAP_DIR/znap.zsh"

if [[ -r "$ZNAP_ENTRYPOINT" ]]; then
    zstyle ':znap:*' repos-dir "$PLUGINS_DIR"
    zstyle ':znap:*:*' git-maintenance off
    source "$ZNAP_ENTRYPOINT"
    znap source ohmyzsh/ohmyzsh lib/{git,clipboard,compfix,completion,key-bindings,termsupport,functions}
    typeset -a PLUGINS=(
        "MichaelAquilina/zsh-auto-notify"
        "zsh-users/zsh-autosuggestions"
        "zsh-users/zsh-completions"
        "zsh-users/zsh-history-substring-search"
        "zsh-users/zsh-syntax-highlighting"
    )
    for plugin in "${PLUGINS[@]}"; do
        if [[ -d "$PLUGINS_DIR/$plugin" ]]; then
            znap source "$plugin" || print -u2 -r -- "failed to source $plugin"
        fi
    done
else
    [[ -o interactive ]] && print -u2 -r -- "zsh: znap is not installed; run zsh:install"
fi

(($+commands[starship])) && eval "$(command starship init zsh)"
##############################################################################################################
## completion contract
# Every custom file containing compdef is sourced after compinit. Keep optional
# completion directories out of fpath when they are not installed.
typeset -gU fpath
typeset -a _zsh_completion_fpath=()
local COMPLETIONS=("$HOME/.local/share/zsh/site-functions" "$HOME/.grok/completions/zsh")
for completion_dir in $COMPLETIONS; do
    [[ -d "$completion_dir" ]] && _zsh_completion_fpath+=("$completion_dir")
done
fpath=("${_zsh_completion_fpath[@]}" "${fpath[@]}")
unset _zsh_completion_fpath completion_dir
autoload -Uz compinit && compinit -C

if (($+functions[znap])); then
    (($+commands[gh])) && znap eval gh-completion 'gh completion -s zsh'
    (($+commands[zoxide])) && znap eval zoxide-init 'zoxide init zsh'
    (($+commands[direnv])) && znap eval direnv-hook 'direnv hook zsh'
    (($+commands[omp])) && znap eval omp-completion 'omp completions zsh'
    (($+commands[herdr])) && znap eval herdr-completion 'herdr completion zsh'
    if [[ -o interactive && -t 0 && -t 1 ]]; then
        (($+commands[fzf])) && znap eval fzf-zsh 'fzf --zsh'
        (($+commands[tv])) && znap eval tv-init 'tv init zsh'
    fi
fi

##############################################################################################################
## source files (cached with znap eval for faster startup)
typeset -a SOURCE=(
    "$HOME/.secrets.sh"
    "$HOME/.cargo/env"
    "$HOME/.railway/env"
    "$HOME/.lmstudio/bin"
    "$DOTFILES/bin/fzf-git"
    "$DOTFILES/config/zsh/alias.sh"
    "$DOTFILES/config/zsh/zstyle.sh"
    "$DOTFILES/config/zsh/history.sh"
    "$DOTFILES/config/zsh/fzf.sh"
    "$DOTFILES/config/zsh/git.sh"
    "$DOTFILES/config/zsh/node.sh"
    "$DOTFILES/config/zsh/completion/node-completion.sh"
    "$DOTFILES/config/zsh/completion/_ai.zsh"
    "$DOTFILES/config/zsh/completion/_worktree.zsh"
    "$DOTFILES/config/zsh/completion/_commit.zsh"
    "$DOTFILES/config/zsh/syntax-highlighting.zsh"
    "${XDG_CONFIG_HOME:-$HOME/.config}/bunsen/env.sh"
)

if [[ -z "$TMUX" ]] && (($+commands[zellij])); then
    SOURCE+=("$DOTFILES/config/zsh/zellij.sh")
fi

for config in "${SOURCE[@]}"; do
    [[ -r "$config" ]] && source "$config"
done

unset SOURCE config

function _zsh_lazy_znap_source() {
    local plugin="$1"
    (($+functions[znap])) || return 1
    if [[ -d "$PLUGINS_DIR/$plugin" ]]; then
        znap source "$plugin"
    else
        znap clone "$plugin" && znap source "$plugin"
    fi
}

if [[ -o interactive && -t 0 && -t 1 && -r "$ZNAP_ENTRYPOINT" ]]; then
    autoload -Uz add-zle-hook-widget
    function _zsh_lazy_load_autopair() {
        add-zle-hook-widget -d line-init _zsh_lazy_load_autopair
        _zsh_lazy_znap_source "hlissner/zsh-autopair" >/dev/null 2>&1 || true
    }
    add-zle-hook-widget line-init _zsh_lazy_load_autopair
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/allangarcez/tools/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/allangarcez/tools/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/allangarcez/tools/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/allangarcez/tools/google-cloud-sdk/completion.zsh.inc'; fi
