return {
    {
        "akinsho/bufferline.nvim",
        opts = {
            options = {
                themable = true,
                indicator = { style = "none" },
                mode = "buffers",
                numbers = "none",
                color_icons = true,
                truncate_names = true,
                show_close_icon = true,
                diagnostics = "nvim_lsp",
                show_buffer_icons = true,
                persist_buffer_sort = true,
                show_tab_indicators = true,
                show_duplicate_prefix = true,
                always_show_bufferline = true,
                auto_toggle_bufferline = true,
                close_command = "bdelete! %d",
                show_buffer_close_icons = true,
                duplicates_across_groups = true,
                left_mouse_command = "buffer %d",
                diagnostics_update_on_event = true,
                right_mouse_command = "bdelete! %d",
                hover = { enabled = true, delay = 200, reveal = { "close" } },
            },
        },
    },
}
