return {
    "pwntester/octo.nvim",
    cmd = "Octo",
    opts = {
        timeout = 10000,
        picker = "snacks",
        enable_builtin = true,
        comment_icon = "▎▎",
        user_icon = " ",
        ghost_icon = "󰊠 ",
        copilot_icon = " ",
        timeline_indent = 4,
        timeline_marker = " ",
        file_panel = { size = 15, use_icons = true },
        resolved_icon = " ",
        outdated_icon = "󰅒 ",
        github_hostname = "",
        left_bubble_delimiter = "",
        right_bubble_delimiter = "",
        use_timeline_icons = true,
        ui = { use_signcolumn = true, use_signstatus = true },
        gh_cmd = "gh",
        reviews = { auto_show_threads = true, focus = "right" },
        reaction_viewer_hint_icon = " ",
        snippet_context_lines = 4,
        commands = {},
        users = "search",
        gh_env = {},
        picker_config = {
            search_static = true,
        },
        timeline_icons = {
            auto_squash = "  ",
            commit_push = "  ",
            comment_deleted = " ",
            force_push = "  ",
            draft = "  ",
            ready = " ",
            commit = "  ",
            deployed = "  ",
            issue_type = "  ",
            label = "  ",
            reference = "  ",
            project = "  ",
            connected = "  ",
            subissue = "  ",
            cross_reference = "  ",
            transferred = "  ",
            parent_issue = "  ",
            head_ref = "  ",
            pinned = "  ",
            milestone = "  ",
            renamed = "  ",
            automatic_base_change_succeeded = "  ",
            base_ref_changed = "  ",
            merged = { "  ", "OctoPurple" },
            closed = {
                closed = { "  ", "OctoRed" },
                completed = { "  ", "OctoPurple" },
                not_planned = { "  ", "OctoGrey" },
                duplicate = { "  ", "OctoGrey" },
            },
            reopened = { "  ", "OctoGreen" },
            assigned = "  ",
            review_requested = "  ",
        },
        issues = {
            order_by = { field = "CREATED_AT", direction = "DESC" },
        },
        pull_requests = {
            order_by = {
                field = "CREATED_AT",
                direction = "DESC",
            },
            always_select_remote_on_create = false,
            use_branch_name_as_title = false,
        },
    },
    dependencies = {
        "folke/snacks.nvim",
        "nvim-lua/plenary.nvim",
        "nvim-tree/nvim-web-devicons",
    },
    keys = {
        {
            "<leader>oi",
            "<CMD>Octo issue list<CR>",
            desc = "List GitHub Issues",
        },
        {
            "<leader>op",
            "<CMD>Octo pr list<CR>",
            desc = "List GitHub PullRequests",
        },
        {
            "<leader>od",
            "<CMD>Octo discussion list<CR>",
            desc = "List GitHub Discussions",
        },
        {
            "<leader>on",
            "<CMD>Octo notification list<CR>",
            desc = "List GitHub Notifications",
        },
        {
            "<leader>os",
            function()
                require("octo.utils").create_base_search_command { include_current_repo = true }
            end,
            desc = "Search GitHub",
        },
    },
}
