return {
    "nvim-treesitter/nvim-treesitter-textobjects",
    {
        "nvim-treesitter/nvim-treesitter-context",
        dependencies = { "nvim-treesitter/nvim-treesitter-textobjects" },
        opts = {
            enable = true,
            multiwindow = true,
            max_lines = 2,
            min_window_height = 0,
            line_numbers = true,
            multiline_threshold = 20,
            trim_scope = "outer",
            mode = "cursor",
            separator = nil,
            zindex = 20,
            on_attach = nil,
        },
    },
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        main = "nvim-treesitter.configs",
        dependencies = { "nvim-treesitter/nvim-treesitter-textobjects", "nvim-treesitter/nvim-treesitter-context" },
        opts = {
            auto_install = true,
            sync_install = true,
            indent = { enable = true },
            highlight = { enable = true },
            incremental_selection = {
                enable = true,
                keymaps = {
                    scope_incremental = false,
                    node_incremental = "<Enter>",
                    node_decremental = "<Backspace>",
                    init_selection = "<Enter>",
                },
            },
            ensure_installed = {
                "bash",
                "c",
                "c_sharp",
                "css",
                "csv",
                "diff",
                "dockerfile",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "html",
                "http",
                "javascript",
                "jq",
                "jsdoc",
                "json",
                "json5",
                "kdl",
                "lua",
                "luadoc",
                "markdown",
                "markdown_inline",
                "prisma",
                "query",
                "regex",
                "styled",
                "sql",
                "tsx",
                "typescript",
                "vim",
                "vimdoc",
                "yaml",
                "zig",
            },
        },
    },
}
