// You must change this devices for your own
export const devices = [
  {
    disable_built_in_keyboard_if_exists: false,
    fn_function_keys: [],
    game_pad_swap_sticks: false,
    identifiers: {
      is_game_pad: false,
      is_keyboard: true,
      is_pointing_device: false,
      product_id: 833,
      vendor_id: 1452,
    },
    ignore: false,
    manipulate_caps_lock_led: true,
    mouse_flip_horizontal_wheel: false,
    mouse_flip_vertical_wheel: false,
    mouse_flip_x: false,
    mouse_flip_y: false,
    mouse_swap_wheels: false,
    mouse_swap_xy: false,
    simple_modifications: [],
    treat_as_built_in_keyboard: false,
  },
  {
    disable_built_in_keyboard_if_exists: false,
    fn_function_keys: [],
    game_pad_swap_sticks: false,
    identifiers: {
      is_game_pad: false,
      is_keyboard: false,
      is_pointing_device: true,
      product_id: 833,
      vendor_id: 1452,
    },
    ignore: true,
    manipulate_caps_lock_led: false,
    mouse_flip_horizontal_wheel: false,
    mouse_flip_vertical_wheel: false,
    mouse_flip_x: false,
    mouse_flip_y: false,
    mouse_swap_wheels: false,
    mouse_swap_xy: false,
    simple_modifications: [],
    treat_as_built_in_keyboard: false,
  },
  {
    disable_built_in_keyboard_if_exists: false,
    fn_function_keys: [],
    game_pad_swap_sticks: false,
    identifiers: {
      is_game_pad: false,
      is_keyboard: true,
      is_pointing_device: true,
      product_id: 8705,
      vendor_id: 4617,
    },
    ignore: false,
    manipulate_caps_lock_led: true,
    mouse_flip_horizontal_wheel: false,
    mouse_flip_vertical_wheel: false,
    mouse_flip_x: false,
    mouse_flip_y: false,
    mouse_swap_wheels: false,
    mouse_swap_xy: false,
    simple_modifications: [],
    treat_as_built_in_keyboard: false,
  },
  {
    disable_built_in_keyboard_if_exists: false,
    fn_function_keys: [],
    game_pad_swap_sticks: false,
    identifiers: {
      is_game_pad: false,
      is_keyboard: false,
      is_pointing_device: true,
      product_id: 8705,
      vendor_id: 4617,
    },
    ignore: false,
    manipulate_caps_lock_led: false,
    mouse_flip_horizontal_wheel: false,
    mouse_flip_vertical_wheel: false,
    mouse_flip_x: false,
    mouse_flip_y: false,
    mouse_swap_wheels: false,
    mouse_swap_xy: false,
    simple_modifications: [],
    treat_as_built_in_keyboard: false,
  },
];
