includes:
  - "~/.shortcuts.yml"

matches:
  - trigger: ":isodate"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%Y-%m-%dT%H:%M:%S"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  - trigger: ":time"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%H:%M"

  - triggers: [":block:", ":mb:"]
    force_clipboard: true
    replace: |-
      ```$|$
      ```

  - triggers: [":code:", ":mc:"]
    force_clipboard: true
    replace: |-
      `$|$`

  - trigger: ":h1:"
    replace: "#"

  - trigger: ":h2:"
    replace: "##"

  - trigger: ":h3:"
    replace: "###"

  - trigger: ":h4:"
    replace: "####"

  - trigger: ":h5:"
    replace: "#####"

  - trigger: ":h6:"
    replace: "######"

  - trigger: ":bold:"
    replace: "**$|$**"

  - trigger: ":italic:"
    replace: "*$|$*"

  - trigger: ":strike:"
    replace: "~~$|$~~"

  - trigger: ":url:"
    replace: "[$|$]()"

  - triggers: [":link:"]
    replace: "[]($|$)"

  - triggers: [":image:", ":img:"]
    replace: "![]($|$)"

  - triggers: [":horizontal:", ":mh:"]
    replace: "___"

  - triggers: [":task:", ":mt:"]
    replace: "- [ ] "

  - triggers: [":taskdone:", ":mtd:"]
    replace: "- [x] "

  - triggers: [":collapse:", ":mcol:"]
    force_clipboard: true
    replace: |-
      <details>
      <summary></summary>

      $|$
      </details>

  - trigger: ":lorem"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          choices:
            - "Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua."
            - "Curabitur blandit tempus ardua ridiculus sed magna."
            - "Inmensae subtilitatis, obscuris et malesuada fames."
            - "Paullum deliquit, ponderibus modulisque suis ratio utitur."
            - "Pellentesque habitant morbi tristique senectus et netus."
            - "A communi observantia non est recedendum."
            - "Unam incolunt Belgae, aliam Aquitani, tertiam."
            - "Magna pars studiorum, prodita quaerimus."
            - "Gallia est omnis divisa in partes tres, quarum."
            - "Phasellus laoreet lorem vel dolor tempus vehicula."
            - "Cras mattis iudicium purus sit amet fermentum."
            - "Nec dubitamus multa iter quae et nos invenerat."
            - "Quo usque tandem abutere, Catilina, patientia nostra?"
            - "Curabitur est gravida et libero vitae dictum."
            - "Quisque ut dolor gravida, placerat libero vel, euismod."
            - "Ullamco laboris nisi ut aliquid ex ea commodi consequat."

  - trigger: ":uuid"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          shell: bash
          cmd: '~/.volta/bin/node -e "console.log(require(''crypto'').randomUUID())"'

  - trigger: ":cpf"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          shell: bash
          cmd: "~/.volta/bin/node ~/dotfiles/bin/cpf"

  - trigger: ":cnpj"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          shell: bash
          cmd: "~/.volta/bin/node ~/dotfiles/bin/cnpj"

  - trigger: ":cep"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          choices:
            - "04538-133"
            - "04543-907"
            - "21530-014"
            - "22740-300"
            - "25060-236"
            - "28957-632"
            - "30260-070"
            - "70040-010"
