# Ip Plugin
POWERLEVEL9K_IP_FOREGROUND='white'
POWERLEVEL9K_IP_BACKGROUND='none'
POWERLEVEL9K_NETWORK_ICON='\uF1d0'
POWERLEVEL9K_IP_INTERFACE='wlan'

# Highlight Syntax
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
ZSH_HIGHLIGHT_PATTERNS+=("rm -rf *" "fg=red")
ZSH_HIGHLIGHT_PATTERNS+=("mv *" "fg=yellow")
ZSH_HIGHLIGHT_STYLES[alias]="fg=yellow,bold"
ZSH_HIGHLIGHT_STYLES[builtin]="fg=white,bold"
ZSH_HIGHLIGHT_STYLES[function]="fg=yellow,bold"
ZSH_HIGHLIGHT_STYLES[command]="fg=white,bold"
ZSH_HIGHLIGHT_STYLES[precommand]="fg=green,bold"
ZSH_HIGHLIGHT_STYLES[hashed-command]="fg=green,bold"
ZSH_HIGHLIGHT_STYLES[commandseparator]="fg=yellow"
ZSH_HIGHLIGHT_STYLES[redirection]="fg=yellow,bold"
ZSH_HIGHLIGHT_STYLES[bracket-level-1]="fg=cyan"
ZSH_HIGHLIGHT_STYLES[bracket-level-2]="fg=green"
ZSH_HIGHLIGHT_STYLES[bracket-level-3]="fg=magenta"
ZSH_HIGHLIGHT_STYLES[bracket-level-4]="fg=yellow"
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
ZSH_HIGHLIGHT_STYLES[default]=none
ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=009
ZSH_HIGHLIGHT_STYLES[hashed-command]=fg=009
ZSH_HIGHLIGHT_STYLES[path]="fg=blue,underline"
ZSH_HIGHLIGHT_STYLES[path_pathseparator]="fg=blue,underline"
ZSH_HIGHLIGHT_STYLES[globbing]=fg=063
ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=white,underline
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=none
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=none
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=none
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=063
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=063
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=009
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=009
ZSH_HIGHLIGHT_STYLES[assign]=none

# RAM Control
POWERLEVEL9K_RAM_ICON='\uF472'
POWERLEVEL9K_RAM_FOREGROUND='white'
POWERLEVEL9K_RAM_BACKGROUND='none'

# Time Control
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0

# Elements in Line Right-Left <>
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status ip ram battery root_indicator)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs dir_writable)

# Batery Elements
POWERLEVEL9K_BATTERY_BACKGROUND="none"
POWERLEVEL9K_BATTERY_VERBOSE=false
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND='cyan'
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND='none'
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND='green'
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND='none'
POWERLEVEL9K_BATTERY_DISCONNECTED='blue'
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND='none'
POWERLEVEL9K_BATTERY_LOW_THRESHOLD='10'
POWERLEVEL9K_BATTERY_LOW_COLOR='red'
POWERLEVEL9K_BATTERY_ICON='\uf1e6'

# Folder Icon
POWERLEVEL9K_FOLDER_ICON='\uF07b'

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{white}> %F{white}"
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""

# Advanced `vcs` color customization
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='green'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='none'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='none'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='none'
POWERLEVEL9K_TIME_FOREGROUND='white'
POWERLEVEL9K_TIME_BACKGROUND='none'
POWERLEVEL9K_VCS_BRANCH_ICON=$'\uF126 '

# Default Colors User
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"

# Mode
POWERLEVEL9K_MODE='flat'

POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M \uF017 %d/%m/%y} \uF073"

# Status OK
POWERLEVEL9K_STATUS_OK_BACKGROUND="none"
POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="none"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
POWERLEVEL9K_STATUS_HIDE_SIGNAME='true'

# Dir_Writable Module
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="yellow"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="none"

# Dir Module
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_DIR_HOME_BACKGROUND="none"
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="none"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="none"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"
POWERLEVEL9K_SHORTEN_DELIMITER=''
POWERLEVEL9K_DIR_PATH_SEPARATOR="\/"
POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=false

# Template Context
POWERLEVEL9K_CONTEXT_TEMPLATE="\ue795 $(whoami)@%m"

# Context Use
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="none"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="white"
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND="red"
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="blue"

POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\uE0B1'  
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$'\uE0B3'
