#!/bin/bash
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="vandalvnl"
CASE_SENSITIVE="false"
DISABLE_UNTRACKED_FILES_DIRTY="true"
ENABLE_CORRECTION="true"
HIST_STAMPS="yyyy-mm-dd"
HYPHEN_INSENSITIVE="true"

plugins=(
  forgit
  git
  docker
  zsh-autosuggestions
  zsh-syntax-highlighting
)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source $ZSH/oh-my-zsh.sh
source $HOME/dotfiles/zsh/export.sh
source $HOME/dotfiles/zsh/alias.sh
source $HOME/.iterm2_shell_integration.zsh;

######################### Setup tools #########################
# Google cloud
if [ -f '$HOME/tools/google-cloud-sdk/path.zsh.inc' ]; then . '$HOME/tools/google-cloud-sdk/path.zsh.inc'; fi
if [ -f '$HOME/tools/google-cloud-sdk/completion.zsh.inc' ]; then . '$HOME/tools/google-cloud-sdk/completion.zsh.inc'; fi

compdef _dotnet_zsh_complete dotnet

# zoxide
eval "$(zoxide init zsh)"

# starship
eval "$(starship init zsh)"

autoload -Uz compinit
compinit

# vi-mode
VI_MODE_CURSOR_NORMAL=2
VI_MODE_CURSOR_VISUAL=6
VI_MODE_CURSOR_INSERT=6
VI_MODE_CURSOR_OPPEND=0

