pager: less
editor: nvim
theme: tokyo-night
spacing: compact
animation: basic
layout: horizontal
load_builtin_themes: true
pager_json: jq
response:
    prettify_json: true
heading:
    visible: true
    show_host: true
    show_version: true
collection_browser:
    position: "right"
keymap:
    commands: ctrl+e
