---@type LazySpec
return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.lua" },
  { import = "astrocommunity.pack.bash" },
  { import = "astrocommunity.pack.json" },
  { import = "astrocommunity.recipes.ai" },
  { import = "astrocommunity.pack.docker" },
  { import = "astrocommunity.test.neotest" },
  { import = "astrocommunity.pack.markdown" },
  { import = "astrocommunity.recipes.vscode" },
  { import = "astrocommunity.pack.tailwindcss" },
  { import = "astrocommunity.quickfix.nvim-bqf" },
  { import = "astrocommunity.utility.lua-json5" },
  { import = "astrocommunity.completion.blink-cmp" },
  { import = "astrocommunity.recipes.vscode-icons" },
  { import = "astrocommunity.colorscheme.catppuccin" },
  { import = "astrocommunity.file-explorer.oil-nvim" },
  { import = "astrocommunity.fuzzy-finder.snacks-picker" },
  { import = "astrocommunity.pack.typescript-all-in-one" },
  { import = "astrocommunity.recipes.picker-nvchad-theme" },
  { import = "astrocommunity.recipes.picker-nvchad-theme" },
  { import = "astrocommunity.recipes.heirline-vscode-winbar" },
  { import = "astrocommunity.recipes.astrolsp-auto-signature-help" },
  { import = "astrocommunity.recipes.astrolsp-no-insert-inlay-hints" },
}
