icons:
    apt: ""
    bash: ""
    brew: ""
    cargo: ""
    deno: "🦖"
    dnf: ""
    docker: ""
    dpkg: ""
    fdisk: ""
    fish: ""
    gh: ""
    git: ""
    gitui: ""
    go: ""
    helm: "󱃾"
    htop: ""
    hx: "󰔤"
    java: ""
    k9s: "󱃾"
    kubectl: "󱃾"
    lazydocker: ""
    lazygit: ""
    lf: ""
    lfcd: ""
    lsd: ""
    lua: ""
    lvim: ""
    mage: ""
    make: ""
    n: ""
    nala: ""
    ni: ""
    node: ""
    npm: ""
    npm: "󰛷"
    nu: ""
    nvim: ""
    pacman: ""
    parted: ""
    paru: ""
    pnpm: ""
    pnpm: ""
    python: ""
    ranger: ""
    ruby: ""
    rustc: ""
    rustup: ""
    ssh: "󰣀"
    tcsh: ""
    tig: ""
    tmux: ""
    top: ""
    topgrade: "󰚰"
    vim: ""
    yarn: ""
    yay: ""
    yazi: ""
    yum: ""
    zsh: ""
    pi: ""
