#!/usr/bin/env bash
source "$HOME/dotfiles/zsh/utils.sh"

NAME="$1"
USER_CONFIG="$HOME/dotfiles/config/tmux/icons.yml"

get_config_value() {
    local key=$1
    local value
    value="$(yq "$key" "$USER_CONFIG")"
    echo "${value-$1}"
}

ICON="$(get_config_value ".icons.\"$NAME\"")"
echo "$ICON $(fishify ${3})"
