[tools]
usage = "1.3.4"
node = "22.15.0"
bun = "1.1.38"
dotnet = "8.0.404"
deno = "2.4.3"
java = "corretto-23.0.1.8.1"
python = "3.13.0"

[settings]
legacy_version_file = true
idiomatic_version_file_enable_tools = ['node']
always_keep_download = false # deleted after install by default
always_keep_install = false  # deleted on failure by default
asdf_compat = true # set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
disable_default_shorthands = false                 # disable the default shorthands, see `MISE_DISABLE_DEFAULT_SHORTHANDS`
env_file = '.env'
experimental = false # enable experimental features
http_timeout = "30"  # set the timeout for http requests in seconds, see `MISE_HTTP_TIMEOUT`
jobs = 16           # number of plugins or runtimes to install in parallel. The default is `4`.
not_found_auto_install = true # see MISE_NOT_FOUND_AUTO_INSTALL
paranoid = false              # see MISE_PARANOID
plugin_autoupdate_last_check_duration = '1 day' # set to 0 to disable updates
raw = false        # set to true to directly pipe plugins to stdin/stdout/stderr
shorthands_file = '~/.config/mise/shorthands.toml' # path to the shorthands file, see `MISE_SHORTHANDS_FILE`
task_output = "prefix"        # see Tasks Runner for more information
verbose = false    # set to true to see full installation output, see `MISE_VERBOSE`
yes = false        # set to true to automatically answer yes to all prompts
